---

- hosts: allservers
  user: root
  pre_tasks:

  - name: update repo cache CentOS
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache Ubuntu
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: allservers
  user: root
  roles:
    - base

- hosts: workstation
  user: root
  roles:
    - workstation

- hosts: webserver
  user: root
  roles:
    - webserver

- hosts: dbserver
  user: root
  roles:
    - dbserver

- hosts: fileserver
  user: root
  roles:
    - fileserver

