---

- hosts: allservers
  user: root
  pre_tasks:

  - name: install updates CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: webserver
  user: root
  tasks:

  - name: install apache and php packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"   

  - name: install apache and php packages for CentOS
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd               
        - php 
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: copy default html file for website
    tags: apache,apache2,httpd
    copy:
      src: Files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: dbserver
  user: root
  tasks:

    - name: install mariadb package CentOS
      tags: centos,db,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package Ubuntu
      tags: ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: fileserver
  user: root
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

