- name: add ssh key for melodie
  authorized_key:
    user: melodie
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINV3qt2G7yApJo/pWfte1IX8D8cNyns2G2rifNK3dN5Z ansible"

- name: generate ssh_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
